### ISSUE TITLE
提示Class 'Typecho\Common' not found

### ISSUE THREAD

**Issue by byebvip** [gogobody/SimpleAdmin#13]
提示更新,删除了旧版之后,然后按照教程重新上传新版,点击启用就是这个提示...文件夹名字也改了

Class 'Typecho\Common' not found

**Comment by gogobody** [comment]
typecho 1.2

**Comment by byebvip** [comment]
> 打字机 1.2

请更新typecho到 1.2.1 以上 ,可是typecho 才1.2.0  很奇怪...

**Comment by gogobody** [comment]
之前修复了请下载最新的
