### ISSUE TITLE
管理评论出现样式错误

### ISSUE THREAD

**Issue by shangxin-lazy** [gogobody/SimpleAdmin#2]
![QQ截图20210725203614](https://user-images.githubusercontent.com/69459353/126899206-28f7c772-7a03-47ac-8ce4-a50613764fe7.png)

如上图，使用版本为1.1.6
PHP版本为7.2

**Comment by shangxin-lazy** [comment]
不仅仅是这个页面，包括这种类似的页面都是这样

**Comment by gogobody** [comment]
开发版typecho 未发现此问题

**Comment by shangxin-lazy** [comment]
> 开发版typecho 未发现此问题

我也是开发版的

**Comment by gogobody** [comment]
update
