### ISSUE TITLE
启用插件时出现404错误

### ISSUE THREAD

**Issue by LeviMarvin** [gogobody/SimpleAdmin#6]
环境：
Nginx 1.21.4
PHP 8.0
Typecho 1.2-RC

问题：启用插件时出现404错误
https://levimarvin.site/action/plugins-edit?activate=SimpleAdmin-1.1.9&_=b738680c7a0d0234deecc3d15e4adca3

**Comment by gogobody** [comment]
可以开启 debug ，贴一下错误代码
